version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: tradingagents-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: tradingagents
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - tradingagents-network

  redis:
    image: redis:7.2-alpine
    container_name: tradingagents-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - tradingagents-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: tradingagents-backend-dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://admin:password@mongodb:27017/tradingagents?authSource=admin
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=development
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - SECRET_KEY=dev-secret-key
      - JWT_SECRET_KEY=dev-jwt-secret-key
    volumes:
      - ./backend:/app
      - ./tradingagents:/app/tradingagents
      - ./logs:/app/logs
      - ./data:/app/data
    depends_on:
      - mongodb
      - redis
    networks:
      - tradingagents-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: tradingagents-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - tradingagents-network

volumes:
  mongodb_data:
  redis_data:

networks:
  tradingagents-network:
    driver: bridge