name: Publish Docker image to GHCR

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag to publish (defaults to VERSION file)"
        required: false
  push:
    tags:
      - 'cn-*'

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/tradingagents-cn

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version
        id: version
        run: |
          if [ -n "${{ github.event.inputs.tag }}" ]; then
            VERSION_TAG="${{ github.event.inputs.tag }}"
          else
            VERSION_TAG=$(cat VERSION)
          fi
          # normalize owner to lowercase for GHCR
          OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "tag=$VERSION_TAG" >> $GITHUB_OUTPUT
          echo "owner_lc=$OWNER_LC" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ steps.version.outputs.owner_lc }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.version.outputs.owner_lc }}/tradingagents-cn:${{ steps.version.outputs.tag }}
            ${{ env.REGISTRY }}/${{ steps.version.outputs.owner_lc }}/tradingagents-cn:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max


